/** ICOPAY / ziobiz PG 공통 UI 클래스 */
export const pg = {
  frame: 'pg-frame',
  frameHead: 'pg-frame-head',
  frameBody: 'pg-frame-body',
  card: 'pg-card',
  cardHead: 'pg-card-head',
  cardBody: 'pg-card-body',
  section: 'pg-section',
  sectionPad: 'pg-section-pad',
  sectionHead: 'pg-section-head',
  stack: 'pg-stack',
  input: 'pg-input',
  select: 'pg-select',
  textarea: 'pg-textarea',
  btn: 'pg-btn',
  btnPrimary: 'pg-btn pg-btn-primary',
  btnSecondary: 'pg-btn pg-btn-secondary',
  table: 'pg-table',
  label: 'pg-label',
  hint: 'pg-hint',
  navItem: 'pg-nav-item',
  tab: 'pg-tab',
  tabActive: 'pg-tab pg-tab-active',
} as const;
