-- AlterEnum
ALTER TYPE "AttachmentPurpose" ADD VALUE 'FUNDING_FORECAST_REPORT';
ALTER TYPE "AttachmentPurpose" ADD VALUE 'SOURCE_OF_FUNDS_DOC';
ALTER TYPE "AttachmentPurpose" ADD VALUE 'JP_TAX_SUPPORT_DOC';
